### ISSUE TITLE
i invited you. invite me?

### ISSUE THREAD

**Issue by webbrowser11** [pikapopcorn/linureOS#1]
i invited you
invite me
pikapopcorn>linureOS>settings>collaborators>add people>webbrowser11

**Comment by pikapopcorn** [comment]
to what?

**Comment by webbrowser11** [comment]
also make the license say:
(c) 2024 Alter Net codes.
also the license is a public license and allows people do do anything with the software. use the alter net codes license i am making.(i will give you it once i am done)

**Comment by pikapopcorn** [comment]
o linire os?

**Comment by webbrowser11** [comment]
yes

**Comment by pikapopcorn** [comment]
ok

**Comment by webbrowser11** [comment]
to linureoS and check skyOS

**Comment by pikapopcorn** [comment]
wait how do you collaborate?

**Comment by webbrowser11** [comment]
ckeck SkyOS i added you or ckeck ur mail

**Comment by pikapopcorn** [comment]
ok

**Comment by pikapopcorn** [comment]
i accepted it!

**Comment by webbrowser11** [comment]
okay now send me an invite

**Comment by pikapopcorn** [comment]
how?

**Comment by pikapopcorn** [comment]
i did!

**Comment by webbrowser11** [comment]
(oh also name the linureOS file LinureOS.py)

**Comment by pikapopcorn** [comment]
ok

**Comment by webbrowser11** [comment]
done

**Comment by webbrowser11** [comment]
i wil do it

**Comment by webbrowser11** [comment]
closing...

**Comment by pikapopcorn** [comment]
nice

**Comment by pikapopcorn** [comment]
what should we work on?

**Comment by pikapopcorn** [comment]
> also make the license say: (c) 2024 Alter Net codes. also the license is a public license and allows people do do anything with the software. use the alter net codes license i am making.(i will give you it once i am done)

ok

**Comment by pikapopcorn** [comment]
are you there?
