### ISSUE TITLE
dev talk

### ISSUE THREAD

**Issue by webbrowser11** [pikapopcorn/linureOS#2]
hi milo you still there?

**Comment by webbrowser11** [comment]
okay i just released the first version!

**Comment by pikapopcorn** [comment]
hi graham!

**Comment by webbrowser11** [comment]
hello

**Comment by webbrowser11** [comment]
are we updating again soon?

**Comment by webbrowser11** [comment]
also feel free to update SkyOS

**Comment by pikapopcorn** [comment]
> also feel free to update SkyOS

ok

**Comment by pikapopcorn** [comment]
> are we updating again soon?

what do you want to update?

**Comment by pikapopcorn** [comment]
I updated it! added easter egg command, and fixed calc function, and fixed elif bug.

**Comment by webbrowser11** [comment]
also are you going to make a new repo?

**Comment by webbrowser11** [comment]
milo its 1:00 okay i guess get on at 4:00? otherwise i might be on for a bit i hate the new policy tho...
